apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-project
spec:
  workspaces:
    - name: output
  params:
    - name: https-git-url
    - name: project-directory-path
  steps:
    - name: git-clone-project
      image: alpine/git
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh

        # init clean project directory
        if [ -d $(params.project-directory-path) ]; then
          echo "Cleaning existing directory: $(params.project-directory-path)..."
          rm -r $(params.project-directory-path)
        fi

        # creating new project directory 
        mkdir -p $(params.project-directory-path)

        # clone repository to project directory
        git clone $(params.https-git-url) $(params.project-directory-path)

