apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: redhat-dependency-analysis
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Security
    tekton.dev/pipelines.minVersion: "0.19.0"
    tekton.dev/tags: Security, Vulnenrability, CVE
    tekton.dev/displayName: "Red Hat Dependency Analysis"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    The Red Hat Dependency Analysis task is an interface between Tekton and Red Hat Dependency Analytics platform.
    It provides vulnerability and compliance analysis for applications dependencies, along with recommendations to address security vulnerabilities and licensing issues.

  workspaces:
    - name: output
      description: Volume backing this workspace is used for input/output of the task.

  params:
    - name: manifest-file-path
      description: Path to target manifest file within the project directory.

    - name: project-directory-path
      description: Path to directory within workspace, where the project is installed.
      default: project-package

    - name: output-file-path
      description: Path to file within workspace, where the analysis report is saved.
      default: redhat-dependency-analysis-report.json

    - name: image
      description: Image where Exhort Javascript API and required dependencies are installed.
      default: quay.io/ecosystem-appeng/exhort-javascript-api:1.0-alpha

  steps:
    - name: redhat-dependency-analysis
      image: $(params.image)
      workingDir: $(workspaces.output.path)
      env:
        - name: EXHORT_SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: exhort
              key: EXHORT_SNYK_TOKEN
      script: |
        #!/bin/sh

        sh /exhort.sh \
          $(echo $(params.project-directory-path)/$(params.manifest-file-path)) \
          $(params.output-file-path)