# A Custom task given for demo purpose to read the report and make decision about build
apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: post-task-setup
spec:
  params:
    - name: output-file-path
    - name: image
  steps:
    - name: post-task-setup
      image: $(params.image)
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh

        printf "Report file data:\n"
        jq . $(params.output-file-path)

        exit_code=$(jq -r '.exit_code' $(params.output-file-path))
        if [ "$exit_code" = "1" ]; then
          printf "\nBUILD FAILED: Failed to generate Dependency Analysis Report" 
          exit 1
        fi

        tot_vul=$(jq .report.total_vulnerabilities  $(params.output-file-path))
        if [ $tot_vul -ge  1 ]; then
          printf "\nBUILD FAILED: Total vulnerability count is: $tot_vul"
          exit 1
        else
          printf "\nBUILD PASSED: Total vulnerability count is 0"
        fi

  workspaces:
    - name: output
