# A Custom task given for demo purpose to download the manifest and install its dependencies.
apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: pre-task-setup
spec:
  params:
    - name: https-git-url
    - name: pkg-installation-directory-path
    - name: image
  steps:
    - name: pre-task-setup
      image: $(params.image)
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh

        # init clean application directory
        if [ -d $(params.pkg-installation-directory-path) ]; then
          echo "Removing existing folder: $(params.pkg-installation-directory-path)..."
          rm -r $(params.pkg-installation-directory-path)
        fi

        mkdir -p $(params.pkg-installation-directory-path)

        # clone repository to application directory
        git clone $(params.https-git-url) $(params.pkg-installation-directory-path)

  workspaces:
    - name: output