apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: pre-task-setup
spec:
  params:
    - name: https-github-url
    - name: pkg-installation-directory-path
      default: application-package
  workspaces:
    - name: output
  steps:
    - name: download-application-package
      image: alpine/git
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh

        if [ -d $(params.pkg-installation-directory-path) ]; then
          echo "Removing existing folder: $(params.pkg-installation-directory-path)..."
          rm -r $(params.pkg-installation-directory-path)
        fi

        mkdir -p $(params.pkg-installation-directory-path)

        git clone $(params.https-github-url) $(params.pkg-installation-directory-path) 
