# Stand alone redhat-codeready-dependency-analysis task run
# Make sure manifest file is in place and application is already downloaded in workspace.
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: redhat-codeready-dependency-analysis-task-run
spec:
  taskRef:
    name: redhat-codeready-dependency-analysis-task

  workspaces:
    - name: output
      persistentvolumeclaim:
        claimName: output

  params:
    - name: manifest-file-path
      value: pom.xml
    - name: output-file-path
      value: redhat-codeready-dependency-analysis-report.json
    - name: pkg-installation-directory-path
      value: application-package
    - name: image
      value: quay.io/ecosystem-appeng/crda-maven:1.0
