# Stand alone redhat-codeready-dependency-analysis task run
# Make sure manifest file is in place and dependencies are already installed inwo workspace.
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: redhat-codeready-dependency-analysis-taskrun
spec:
  taskRef:
    name: redhat-codeready-dependency-analysis

  workspaces:
    - name: output
      persistentvolumeclaim:
        claimName: output

  params:
    - name: manifest-file-path
      value: {{MANIFEST_FILE_PATH}}     
    - name: pkg-installation-directory-path
      value: application-package
    - name: output-file-path
      value: redhat-codeready-dependency-analysis-report.json
    - name: image
      value: quay.io/ecosystem-appeng/crda:1.0
